import { useState, useEffect, useMemo } from "react";
import { useTheme } from "../ThemeContext.jsx";
import { askClaude, P_BRAIN_OPS, P_BRAIN_ASK } from "../lib/claude.js";
import { fetchBrainNotes, saveBrainNote, deleteBrainNote, fetchTranslatedLangs } from "../lib/supabase.js";
import { Btn, Spinner, Tag } from "./UI.jsx";

// ── helpers ───────────────────────────────────────────────────────────────────
const slug = s => (s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const parseLinks = body => {
  const out = new Set();
  const re = /\[\[([^\]]+)\]\]/g; let m;
  while ((m = re.exec(body || ""))) out.add(m[1].trim());
  return [...out];
};

// ── the seed "how the app works" notes (authored from the real source) ─────────
const SEED = [
  { title: "Overview", kind: "doc", body:
`MangaMultiVerse is a React 18 + Vite SPA (vanilla JS, inline-style JSX, no TypeScript). Readers browse a public feed of AI-authored manga; creators build stories in the [[Studio Flow]].

- Backend: Supabase (auth + Postgres REST). See [[Data Layer (Supabase)]] and [[Auth & Session]].
- AI: Anthropic Claude for text, Fal.ai for images. See [[AI Engine (claude.js)]].
- Reading + translation: [[Reader Flow]], [[Translation System]].
- Shipping: [[Deploy (Vercel)]].
- Watch-outs before scaling: [[Known Scale Cliffs]].` },
  { title: "Data Layer (Supabase)", kind: "doc", body:
`All DB access goes through the \`sb\` helper in \`src/lib/supabase.js\` (get/post/patch/del/upsert), which auto-refreshes a lapsed JWT once on 401.

- \`stories\` — one row per story; extra fields ride inside the \`script\` jsonb, filtered on save by the \`DB_COLS\` allowlist.
- \`translations\` — one row per (story, language); see [[Translation System]].
- \`brain_notes\` — this vault (admin-only).
- \`profiles\` — id, username, email, role, credits.

Adding a story field needs BOTH a \`DB_COLS\` edit AND a manual \`ALTER TABLE\` — see [[Known Scale Cliffs]].` },
  { title: "AI Engine (claude.js)", kind: "doc", body:
`\`src/lib/claude.js\` holds every AI call and prompt.

- \`askClaude\` → Anthropic (model claude-haiku-4-5), 8000-token cap, 90s timeout, salvages truncated JSON.
- \`generatePanelImage\` → Fal.ai with model failover (flux/schnell → sdxl → flux-lora) and reseed-on-black-image retries.
- Prompt builders: \`P_STORY\`, \`P_SCRIPT\`, \`P_CHAR\`, \`P_VOICES\`, \`P_TRANSLATE\`, and the brain's \`P_BRAIN_OPS\` / \`P_BRAIN_ASK\`.

Keys are read from \`VITE_*\` env — the big risk in [[Known Scale Cliffs]].` },
  { title: "Studio Flow", kind: "doc", body:
`\`src/components/Studio.jsx\` is the creator editor: seed → story → script → character brief → voices → panels → publish.

- Panels are generated by \`genImagesForPanel\` / \`genPanels\` (2-wide concurrency).
- \`↻ Redo\` = \`regenerateOnePanel\`; keeps the old image until the new one lands.
- \`↺ Revert to published\` restores the cloud panels — free, no API.
- Publish embeds art_style/mono/layout and pre-translates languages — see [[Translation System]].
- Credits are charged here (client-side — see [[Known Scale Cliffs]]).` },
  { title: "Reader Flow", kind: "doc", body:
`\`src/components/MangaReader.jsx\` renders a published story. Classic manga = on-art bubbles; webtoon = vertical scroll.

- Monochrome stories get a grayscale display filter.
- Character intro nameplates + narrator boxes come from \`mangaBubbles.jsx\`.
- Language switch triggers [[Translation System]].` },
  { title: "Translation System", kind: "doc", body:
`Translations are stored in their OWN \`translations\` table (keyed \`storyId_language\`) so they never bloat the feed. See [[Data Layer (Supabase)]].

- Pre-generated at publish and in the Studio's Translate tab.
- Per-panel signatures (\`_sigs\`) mean only panels whose DIALOGUE changed get re-translated; a pure art redraw does not.
- Readers get stored translations instantly; an un-cached language translates live on demand (\`translateChapter\`) — an uncharged cost path noted in [[Known Scale Cliffs]].` },
  { title: "Auth & Session", kind: "doc", body:
`Supabase email/password auth in \`src/lib/supabase.js\`. JWT (~1h) with refresh-token rotation, de-duped through \`ensureFreshToken\` to avoid a rotation race.

- \`registerSession\` wires refresh/expired callbacks to App state + localStorage.
- \`profiles.role\` exists but is only ever "creator" today; admin (this Brain, the Agents page) must be granted by hand — see [[Known Scale Cliffs]].` },
  { title: "Deploy (Vercel)", kind: "doc", body:
`Hosted on Vercel; \`vercel.json\` is an SPA catch-all rewrite. \`npm run build\` (Vite) → deploy.

- Two serverless proxies exist (\`api/claude.js\`, \`api/image.js\`) but are currently bypassed because the \`VITE_*\` keys are present.
- Every catalog/price/prompt is a compile-time constant: changing it means a redeploy. See [[Known Scale Cliffs]].` },
  { title: "Known Scale Cliffs", kind: "doc", body:
`From the developer-dependency audit — the things that need a developer *every time* at scale:

1. **Shared browser-exposed API keys** = one bill + one rate limit for all users; keys are extractable.
2. **Client-side credits** — bypassable; logged-out readers and publish pre-translation are uncharged. See [[Translation System]].
3. **No moderation/reporting** — removing bad content = hand-editing Supabase. See [[Moderation Watch]].
4. **Zero observability** — errors are console-only; you hear about breakage from complaints.
5. **Manual, unversioned schema/RLS** (this table's SQL is the first committed one).
6. **No feed pagination** — the homepage pulls the whole corpus.

Securing 1 & 2 is "Phase 1" — recommended next after this Brain.` },
];

// ── inline markdown (bold, code, links, [[wikilinks]]) → React nodes ───────────
function renderInline(text, onOpen, C, kp) {
  const RE = /\[\[([^\]]+)\]\]|\*\*([^*]+)\*\*|\[([^\]]+)\]\(([^)]+)\)|`([^`]+)`/g;
  const out = []; let last = 0, m, i = 0;
  while ((m = RE.exec(text))) {
    if (m.index > last) out.push(text.slice(last, m.index));
    if (m[1] != null) {
      const t = m[1].trim();
      out.push(<span key={`${kp}-${i}`} onClick={() => onOpen(t)} style={{ color: C.purpleL, cursor: "pointer", borderBottom: `1px dotted ${C.purple}` }}>{t}</span>);
    } else if (m[2] != null) {
      out.push(<strong key={`${kp}-${i}`} style={{ color: C.text }}>{m[2]}</strong>);
    } else if (m[3] != null) {
      out.push(<a key={`${kp}-${i}`} href={m[4]} target="_blank" rel="noreferrer" style={{ color: C.teal }}>{m[3]}</a>);
    } else if (m[5] != null) {
      out.push(<code key={`${kp}-${i}`} style={{ background: C.bg, padding: "1px 5px", borderRadius: 4, fontSize: 12, fontFamily: "monospace" }}>{m[5]}</code>);
    }
    last = m.index + m[0].length; i++;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}

function Markdown({ text, onOpen, C }) {
  const lines = (text || "").split("\n");
  const blocks = []; let list = null;
  const flush = () => { if (list) { blocks.push(<ul key={`ul${blocks.length}`} style={{ margin: "6px 0", paddingLeft: 20 }}>{list}</ul>); list = null; } };
  lines.forEach((ln, idx) => {
    const k = `l${idx}`;
    if (/^###\s/.test(ln)) { flush(); blocks.push(<div key={k} style={{ fontSize: 13, fontWeight: 600, color: C.text, margin: "10px 0 4px" }}>{renderInline(ln.slice(4), onOpen, C, k)}</div>); }
    else if (/^##\s/.test(ln)) { flush(); blocks.push(<div key={k} style={{ fontSize: 15, fontWeight: 700, color: C.text, margin: "12px 0 5px" }}>{renderInline(ln.slice(3), onOpen, C, k)}</div>); }
    else if (/^#\s/.test(ln)) { flush(); blocks.push(<div key={k} style={{ fontSize: 17, fontWeight: 700, color: C.text, margin: "6px 0 6px" }}>{renderInline(ln.slice(2), onOpen, C, k)}</div>); }
    else if (/^\s*[-*]\s/.test(ln)) { (list = list || []).push(<li key={k} style={{ fontSize: 13, color: C.text, lineHeight: 1.6 }}>{renderInline(ln.replace(/^\s*[-*]\s/, ""), onOpen, C, k)}</li>); }
    else if (ln.trim() === "") { flush(); }
    else { flush(); blocks.push(<div key={k} style={{ fontSize: 13, color: C.text, lineHeight: 1.65, margin: "4px 0" }}>{renderInline(ln, onOpen, C, k)}</div>); }
  });
  flush();
  return <div>{blocks}</div>;
}

// ── Obsidian-style graph (hand-rolled SVG) ─────────────────────────────────────
function Graph({ notes, activeTitle, onOpen, C }) {
  const W = 640, H = 440, cx = W / 2, cy = H / 2, r = Math.min(W, H) / 2 - 60;
  const byTitle = useMemo(() => { const m = {}; notes.forEach(n => { m[n.title.toLowerCase()] = n; }); return m; }, [notes]);
  const pos = useMemo(() => {
    const p = {}; const n = notes.length || 1;
    notes.forEach((note, i) => { const a = (i / n) * Math.PI * 2 - Math.PI / 2; p[note.title] = { x: cx + r * Math.cos(a), y: cy + r * Math.sin(a) }; });
    return p;
  }, [notes]);
  const kindColor = k => k === "ops" ? C.gold : k === "doc" ? C.purple : C.teal;
  const edges = [];
  notes.forEach(n => (n.links || []).forEach(t => { const tgt = byTitle[(t || "").toLowerCase()]; if (tgt && pos[n.title] && pos[tgt.title]) edges.push([pos[n.title], pos[tgt.title], `${n.title}->${t}`]); }));
  return (
    <svg viewBox={`0 0 ${W} ${H}`} style={{ width: "100%", height: "auto", background: C.bg, borderRadius: 12, border: `0.5px solid ${C.border}` }}>
      {edges.map(([a, b, key]) => <line key={key} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={C.border2} strokeWidth={1} />)}
      {notes.map(n => {
        const p = pos[n.title]; if (!p) return null;
        const on = n.title === activeTitle;
        return (
          <g key={n.title} onClick={() => onOpen(n.title)} style={{ cursor: "pointer" }}>
            <circle cx={p.x} cy={p.y} r={on ? 9 : 6} fill={kindColor(n.kind)} stroke={on ? C.text : "transparent"} strokeWidth={1.5} />
            <text x={p.x} y={p.y - 12} textAnchor="middle" fontSize={10} fill={on ? C.text : C.muted} style={{ pointerEvents: "none" }}>{n.title}</text>
          </g>
        );
      })}
    </svg>
  );
}

// ── main page ──────────────────────────────────────────────────────────────────
export default function BrainPage({ auth, published = [], db }) {
  const C = useTheme();
  const token = auth?.token;
  const [notes, setNotes] = useState([]);
  const [activeId, setActiveId] = useState(null);
  const [query, setQuery] = useState("");
  const [view, setView] = useState("read");     // 'read' | 'graph'
  const [editing, setEditing] = useState(null);  // {title, body}
  const [loading, setLoading] = useState(true);
  const [opsLoading, setOpsLoading] = useState(false);
  const [ask, setAsk] = useState("");
  const [answer, setAnswer] = useState(null);
  const [asking, setAsking] = useState(false);
  const [toast, setToast] = useState("");

  const flash = m => { setToast(m); setTimeout(() => setToast(""), 2600); };

  // Load — seed the doc notes on first run (best-effort persist; works in-memory even pre-SQL).
  useEffect(() => {
    let active = true;
    (async () => {
      const rows = await fetchBrainNotes(token);
      if (!active) return;
      if (rows.length) { setNotes(rows); setActiveId(rows[0].id); }
      else {
        const seeded = SEED.map(s => ({ id: `doc_${slug(s.title)}`, ...s, links: parseLinks(s.body), tags: [], updated_at: new Date().toISOString() }));
        setNotes(seeded); setActiveId(seeded[0].id);
        for (const n of seeded) saveBrainNote(n, token); // best-effort
      }
      setLoading(false);
    })();
    return () => { active = false; };
  }, [token]);

  const active = notes.find(n => n.id === activeId) || null;
  const openByTitle = t => { const n = notes.find(x => x.title.toLowerCase() === (t || "").toLowerCase()); if (n) { setActiveId(n.id); setEditing(null); setView("read"); } else flash(`No note "${t}" yet`); };
  const backlinks = active ? notes.filter(n => n.id !== active.id && (n.links || []).some(l => l.toLowerCase() === active.title.toLowerCase())) : [];

  const filtered = notes.filter(n => !query || n.title.toLowerCase().includes(query.toLowerCase()) || (n.body || "").toLowerCase().includes(query.toLowerCase()));
  const groups = [["doc", "How it works"], ["ops", "Live ops"], ["note", "Notes"]];

  const persist = async (note) => { setNotes(prev => { const i = prev.findIndex(x => x.id === note.id); return i >= 0 ? prev.map(x => x.id === note.id ? note : x) : [note, ...prev]; }); await saveBrainNote(note, token); };

  const saveEdit = async () => {
    const t = (editing.title || "Untitled").trim();
    const note = { ...(active && active.id === editing.id ? active : {}), id: editing.id, title: t, body: editing.body, kind: editing.kind || "note", links: parseLinks(editing.body), tags: [], updated_at: new Date().toISOString() };
    await persist(note); setActiveId(note.id); setEditing(null); flash("Saved");
  };
  const newNote = () => { const id = `note_${Date.now()}`; setEditing({ id, title: "Untitled", body: "", kind: "note" }); };
  const removeNote = async (n) => { if (!window.confirm(`Delete "${n.title}"?`)) return; setNotes(prev => prev.filter(x => x.id !== n.id)); if (activeId === n.id) setActiveId(notes[0]?.id || null); await deleteBrainNote(n.id, token); flash("Deleted"); };

  // ── Ops Synthesizer ──
  const refreshOps = async () => {
    setOpsLoading(true);
    try {
      const genre = {}, authors = {}, missingArt = [], warns = {};
      published.forEach(s => {
        (s.genre_tags || []).forEach(g => { genre[g] = (genre[g] || 0) + 1; });
        const a = s.author_name || s.author || "Unknown"; authors[a] = (authors[a] || 0) + 1;
        const panels = s.script?.panels?.length || 0;
        const art = Object.keys(s.script?.panel_images || {}).length;
        if (panels && !art) missingArt.push(s.title);
        const w = s.content_warning || s.script?.content_warning; if (w && w !== "none") warns[w] = (warns[w] || 0) + 1;
      });
      const newest = [...published].sort((a, b) => (b.updated_at || "").localeCompare(a.updated_at || "")).slice(0, 6).map(s => ({ title: s.title, author: s.author_name || s.author, updated_at: s.updated_at }));
      // Sample translation coverage on the newest handful (cheap; admin action).
      const sample = newest.slice(0, 6);
      const cov = [];
      for (const s0 of sample) { const full = published.find(p => p.title === s0.title); if (full?.id) { const langs = await fetchTranslatedLangs(full.id); cov.push({ title: s0.title, langs: langs.length }); } }
      const snapshot = { total_published: published.length, newest, genre_counts: genre, top_authors: authors, health: { missing_art: missingArt, count: missingArt.length }, content_warnings: warns, translation_coverage: { sampled: cov.length, translated: cov } };
      const r = await askClaude(P_BRAIN_OPS(snapshot), () => {});
      const list = r?.notes || [];
      if (!list.length) { flash("Ops synth returned nothing — try again"); setOpsLoading(false); return; }
      for (const n of list) { const note = { id: `ops_${slug(n.title)}`, title: n.title, body: n.body || "", kind: "ops", links: parseLinks(n.body || ""), tags: [], updated_at: new Date().toISOString() }; await persist(note); }
      flash(`Refreshed ${list.length} ops notes`);
      setView("read");
      setActiveId(`ops_${slug(list[0].title)}`);
    } catch (e) { flash("Ops synth failed: " + e.message); }
    setOpsLoading(false);
  };

  // ── Ask the Brain ──
  const runAsk = async () => {
    if (!ask.trim()) return;
    setAsking(true); setAnswer(null);
    const q = ask.toLowerCase().split(/\s+/).filter(w => w.length > 3);
    const scored = notes.map(n => { const hay = (n.title + " " + n.body).toLowerCase(); const score = q.reduce((s, w) => s + (hay.includes(w) ? 1 : 0), 0) + (q.some(w => n.title.toLowerCase().includes(w)) ? 2 : 0); return { n, score }; })
      .sort((a, b) => b.score - a.score).filter(x => x.score > 0).slice(0, 6).map(x => x.n);
    const context = scored.length ? scored : notes.slice(0, 6);
    try { const r = await askClaude(P_BRAIN_ASK(ask, context), () => {}); setAnswer(r || { answer: "No answer.", used: [] }); }
    catch (e) { setAnswer({ answer: "Failed: " + e.message, used: [] }); }
    setAsking(false);
  };

  const inp = { width: "100%", padding: "9px 12px", borderRadius: 8, border: `0.5px solid ${C.border2}`, background: C.card, color: C.text, fontSize: 13, fontFamily: "inherit", outline: "none" };
  const kindTag = k => k === "ops" ? C.gold : k === "doc" ? C.purple : C.teal;

  return (
    <div style={{ maxWidth: 1100, margin: "0 auto" }}>
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 4 }}>
          <div style={{ width: 8, height: 8, borderRadius: "50%", background: `linear-gradient(135deg,${C.purple},${C.pink})`, boxShadow: `0 0 8px ${C.purple}88` }} />
          <div style={{ fontSize: 11, color: C.purple, textTransform: "uppercase", letterSpacing: "0.12em", fontWeight: 500 }}>Admin · Private</div>
        </div>
        <div style={{ fontSize: 22, fontWeight: 700, fontFamily: "'Cinzel',serif", color: C.text }}>🧠 The Brain</div>
        <div style={{ fontSize: 13, color: C.muted, marginTop: 4 }}>How the app works + live platform state, linked like Obsidian. Ask it anything.</div>
      </div>

      {/* Ask the Brain */}
      <div style={{ background: C.surf, border: `0.5px solid ${C.border}`, borderRadius: 14, padding: 16, marginBottom: 18 }}>
        <div style={{ display: "flex", gap: 10 }}>
          <input value={ask} onChange={e => setAsk(e.target.value)} onKeyDown={e => e.key === "Enter" && runAsk()} placeholder="Ask the brain — e.g. how are translations stored? what's broken right now?" style={inp} />
          <Btn v="pri" onClick={runAsk} disabled={asking || !ask.trim()} sx={{ whiteSpace: "nowrap" }}>{asking ? <><Spinner size={13} /> Thinking…</> : "Ask"}</Btn>
        </div>
        {answer && (
          <div style={{ marginTop: 12, padding: 14, background: C.card, borderRadius: 10, border: `0.5px solid ${C.border}` }}>
            <Markdown text={answer.answer} onOpen={openByTitle} C={C} />
            {answer.used?.length > 0 && <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginTop: 10 }}>{answer.used.map(u => <button key={u} onClick={() => openByTitle(u)} style={{ fontSize: 11, padding: "3px 9px", borderRadius: 6, border: `0.5px solid ${C.purple}`, background: C.purple + "18", color: C.purpleL, cursor: "pointer", fontFamily: "inherit" }}>[[{u}]]</button>)}</div>}
          </div>
        )}
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "260px 1fr", gap: 16, alignItems: "start" }}>
        {/* Sidebar */}
        <div style={{ background: C.surf, border: `0.5px solid ${C.border}`, borderRadius: 14, padding: 12 }}>
          <input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search notes…" style={{ ...inp, marginBottom: 10 }} />
          <div style={{ display: "flex", gap: 6, marginBottom: 12 }}>
            <Btn onClick={newNote} sx={{ flex: 1, fontSize: 12, padding: "7px 0", justifyContent: "center" }}>+ Note</Btn>
            <Btn onClick={refreshOps} disabled={opsLoading} sx={{ flex: 1, fontSize: 12, padding: "7px 0", justifyContent: "center" }}>{opsLoading ? <Spinner size={12} /> : "↻ Ops"}</Btn>
          </div>
          {loading && <div style={{ color: C.muted, fontSize: 12, padding: 8 }}><Spinner size={13} /> Loading…</div>}
          {groups.map(([kind, label]) => {
            const items = filtered.filter(n => n.kind === kind);
            if (!items.length) return null;
            return (
              <div key={kind} style={{ marginBottom: 12 }}>
                <div style={{ fontSize: 9, color: C.muted, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 5 }}>{label}</div>
                {items.map(n => (
                  <button key={n.id} onClick={() => { setActiveId(n.id); setEditing(null); }} style={{ display: "block", width: "100%", textAlign: "left", padding: "7px 9px", borderRadius: 7, marginBottom: 3, border: `0.5px solid ${activeId === n.id ? kindTag(kind) : "transparent"}`, background: activeId === n.id ? kindTag(kind) + "18" : "transparent", color: activeId === n.id ? C.text : C.muted, cursor: "pointer", fontFamily: "inherit", fontSize: 12.5 }}>{n.title}</button>
                ))}
              </div>
            );
          })}
        </div>

        {/* Main pane */}
        <div style={{ background: C.surf, border: `0.5px solid ${C.border}`, borderRadius: 14, padding: 20, minHeight: 360 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14, gap: 10 }}>
            <div style={{ display: "flex", gap: 6 }}>
              <button onClick={() => setView("read")} style={{ fontSize: 12, padding: "5px 12px", borderRadius: 7, border: `0.5px solid ${view === "read" ? C.purple : C.border}`, background: view === "read" ? C.purple + "18" : "transparent", color: view === "read" ? C.purpleL : C.muted, cursor: "pointer", fontFamily: "inherit" }}>Read</button>
              <button onClick={() => setView("graph")} style={{ fontSize: 12, padding: "5px 12px", borderRadius: 7, border: `0.5px solid ${view === "graph" ? C.purple : C.border}`, background: view === "graph" ? C.purple + "18" : "transparent", color: view === "graph" ? C.purpleL : C.muted, cursor: "pointer", fontFamily: "inherit" }}>Graph</button>
            </div>
            {view === "read" && active && !editing && (
              <div style={{ display: "flex", gap: 6 }}>
                <button onClick={() => setEditing({ id: active.id, title: active.title, body: active.body, kind: active.kind })} style={{ fontSize: 12, padding: "5px 12px", borderRadius: 7, border: `0.5px solid ${C.border}`, background: "transparent", color: C.muted, cursor: "pointer", fontFamily: "inherit" }}>Edit</button>
                <button onClick={() => removeNote(active)} style={{ fontSize: 12, padding: "5px 10px", borderRadius: 7, border: `0.5px solid ${C.border}`, background: "transparent", color: "#e24b4a", cursor: "pointer", fontFamily: "inherit" }}>Delete</button>
              </div>
            )}
          </div>

          {view === "graph" ? (
            <Graph notes={notes} activeTitle={active?.title} onOpen={openByTitle} C={C} />
          ) : editing ? (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              <input value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} placeholder="Note title" style={{ ...inp, fontSize: 15, fontWeight: 600 }} />
              <textarea value={editing.body} onChange={e => setEditing({ ...editing, body: e.target.value })} rows={16} placeholder="Markdown. Link other notes with [[Title]]." style={{ ...inp, resize: "vertical", lineHeight: 1.6, fontFamily: "monospace", fontSize: 12.5 }} />
              <div style={{ display: "flex", gap: 8 }}>
                <Btn v="pri" onClick={saveEdit}>Save</Btn>
                <Btn onClick={() => setEditing(null)}>Cancel</Btn>
              </div>
            </div>
          ) : active ? (
            <div>
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
                <div style={{ fontSize: 20, fontWeight: 700, fontFamily: "'Cinzel',serif", color: C.text }}>{active.title}</div>
                <Tag c={kindTag(active.kind)}>{active.kind}</Tag>
              </div>
              <Markdown text={active.body} onOpen={openByTitle} C={C} />
              {backlinks.length > 0 && (
                <div style={{ marginTop: 20, paddingTop: 14, borderTop: `0.5px solid ${C.border}` }}>
                  <div style={{ fontSize: 10, color: C.muted, textTransform: "uppercase", letterSpacing: "0.07em", marginBottom: 8 }}>Linked from</div>
                  <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{backlinks.map(b => <button key={b.id} onClick={() => setActiveId(b.id)} style={{ fontSize: 11, padding: "3px 9px", borderRadius: 6, border: `0.5px solid ${C.border}`, background: C.card, color: C.muted, cursor: "pointer", fontFamily: "inherit" }}>{b.title}</button>)}</div>
                </div>
              )}
            </div>
          ) : (
            <div style={{ color: C.muted, fontSize: 13, padding: 30, textAlign: "center" }}>Select a note, or click ↻ Ops to synthesize live platform notes.</div>
          )}
        </div>
      </div>

      {toast && <div style={{ position: "fixed", bottom: 24, left: "50%", transform: "translateX(-50%)", background: C.card, border: `0.5px solid ${C.border2}`, borderRadius: 10, padding: "10px 18px", fontSize: 13, color: C.text, zIndex: 300, boxShadow: "0 8px 24px rgba(0,0,0,0.3)" }}>{toast}</div>}
    </div>
  );
}
